import ThemeSelector from '@/components/theme-selector'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CalcShare',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='p-3'>
      <body className={inter.className}>
        <header className='flex justify-between'>
          <div className='flex'>
            <Link href="/">CalcShare</Link>
          </div>
          <div className='flex justify-left'>
            <ThemeSelector />
          </div>
        </header>
        <hr className='m-4' />
        <main className="min-h-screen">
          {children}
        </main>
      </body>
    </html>
  )
}
