import { Inter } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CalcShare',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Link href="/">CalcShare</Link>
        </header>
        <hr className='m-4' />
        <main className="min-h-screen">
          {children}
        </main>
      </body>
    </html>
  )
}
